services:
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    volumes:
      - html:/var/www/html:rw
      - ../:/var/www/html/wp-content/plugins/payment-methods-report-woocommerce:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp

  db:
    image: mariadb:11.3
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"

    volumes:
      - db_data:/var/lib/mysql:Z

  php:
    build:
      context: ./php
      target: plugin
    restart: unless-stopped
    volumes:
      - html:/var/www/html:rw
      - ../:/var/www/html/wp-content/plugins/payment-methods-report-woocommerce:rw
    working_dir: /var/www/html/wp-content/plugins/payment-methods-report-woocommerce
    depends_on:
      - nginx
      - db

  node:
    image: node:16-alpine
    restart: no
    volumes:
      - ../:/app:rw
    working_dir: /app

volumes:
  html:
  db_data:
