services:
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    volumes:
      - www:/var/www:rw
      - ../:/var/www/web/app/plugins/payment-methods-report-woocommerce:ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp

  db:
    image: mariadb:11.3
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
      MARIADB_DATABASE: "wordpress"
    volumes:
      - db_data:/var/lib/mysql:Z

  php:
    build:
      context: ./php
      target: plugin
    restart: unless-stopped
    volumes:
      - www:/var/www:rw
      - ../:/var/www/web/app/plugins/payment-methods-report-woocommerce:rw
    env_file:
      - ./php/.env
    depends_on:
      - nginx
      - db

  node:
    image: node:20.12.2-alpine
    restart: no
    volumes:
      - ../:/app:rw
    working_dir: /app
    environment:
      NODE_OPTIONS: "--openssl-legacy-provider"

volumes:
  www:
  db_data:
